apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true" 
  REDIS_URL: {{ .Values.configMap.REDIS_URL }} 
  MONGO_URL: {{ .Values.configMap.MONGO_URL }}
  